# postgres

version: '3.7'
services:
  postgres:
    image: postgres:15-alpine
    container_name: meal-planner-postgres
    environment:
      POSTGRES_USER: meal-planner
      POSTGRES_PASSWORD: meal-planner
      POSTGRES_DB: meal-planner
    ports:
      - "7432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
